language: go
install: true
sudo: false

go:
  - 1.12.x

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1

script:
  - diff -u <(echo -n) <(gofmt -d $(find . -type f -name '*.go' -not -path "./vendor/*")) 
  - make && make test
  - XDEV_IMAGE=xuper/emcc:1.38.30 make contractsdk
  - cd ./core/test && bash ci_pipeline.sh

cache:
  directories:
    - .cache
